import type { ImageSignals } from './imageAnalysis';

interface RoastTemplate {
    category: string;
    weight: number;
    condition: (s: ImageSignals) => boolean;
    templates: { [key: string]: string[] }; // keyed by intensity
}

const ROAST_TEMPLATES: RoastTemplate[] = [
    {
        category: "no_face",
        weight: 10.0,
        condition: (s) => !s.faceDetected,
        templates: {
            'playful': [
                "I can't roast you if you're invisible.",
                "Is this a landscape photo or do you just lack presence?",
                "Trying to hide from the AI? I respect it.",
                "I see a wall, a floor, and zero personality.",
                "Ghosted by your own reflection?",
                "Are you the invisible man?",
                "Camera shy or just non-existent?",
                "I see dead pixels.",
                "Is this abstract art? Because I don't get it.",
                "I'm roasting the air right now.",
                "Did John Cena take this?",
                "Loading personality... 404 Failed.",
                "You're hiding better than my dad.",
                "Is this a texture pack glitch?",
                "POV: You have no rizz.",
                "Stealth mode: Activated.",
                "You're giving nothing. Absolutely nothing.",
                "Go girl, give us nothing!",
                "I assume you're the wall?",
                "Nice wallpaper.",
                "I'd roast you but you didn't show up.",
                "I can't face you if you don't have one.",
                "Are you a vampire?",
                "Microscope needed for this one.",
                "I see you're practicing your camouflage."
            ],
            'no-mercy': [
                "404 Error: Face not found.",
                "You have the charisma of an empty room.",
                "Did you forget to stand in front of the camera?",
                "I'm looking for a face but all I see is disappointment.",
                "You have less presence than a substitute teacher.",
                "If you were a spice, you'd be flour.",
                "I've seen more personality in a stock photo.",
                "You're clearly not the main character.",
                "Even the AI is ignoring you.",
                "404: Clout not found.",
                "You're as memorable as a terms of service agreement.",
                "Are you allergic to being perceived?",
                "This photo is a waste of pixels.",
                "You look like a deleted scene.",
                "I bet you get ignored in group chats too.",
                "Your aura is -1000.",
                "Stop hiding, it won't help.",
                "This is giving witness protection program.",
                "You literally zeroed out the algorithm.",
                "Face card declined.",
                "Your existence is currently buffering.",
                "I can't even roast you, you're that irrelevant.",
                "You look like a generic placeholder image.",
                "Access denied: No personality detected.",
                "You're the human equivalent of static noise."
            ],
            'career-ending': [
                "Your existence is so negligible even AI can't perceive it.",
                "This is a photo of what your friends see when they close their eyes.",
                "You're not even a main character in your own selfie.",
                "If I can't find your face, how will anyone else ever find you attractive?",
                "This is proof that the universe doesn't notice you.",
                "You are the human equivalent of a skipped ad.",
                "I tried to find your face but found your lack of potential instead.",
                "You're so irrelevant the camera refused to focus.",
                "Your best angle is clearly 'not there'.",
                "You effectively don't exist.",
                "Imagine being this unmemorable.",
                "A blank canvas has more potential than you.",
                "You're the side character in your own life.",
                "Even your reflection quit.",
                "This image has the same energy as your love life: empty.",
                "You're giving 'participation award' energy.",
                "I'd call you ugly but I can't even see you to confirm.",
                "You achieved invisibility through sheer boringness.",
                "Go back to the lobby, NPC.",
                "System error: User has no soul.",
                "You're barely a concept, let alone a person.",
                "Unremarkable is an understatement.",
                "You look like void space.",
                "I've seen more life in a vacuum.",
                "You are the visual definition of silence."
            ]
        }
    },
    {
        category: "bad_quality",
        weight: 2.0,
        condition: (s) => s.isDark || s.blurScore < 0.2,
        templates: {
            'playful': [
                "Did you take this photo inside a microwave?",
                "I love the 'cryptid sighting' aesthetic.",
                "Paying your electricity bill is a good investment, just saying.",
                "Focus is a feature, not a bug.",
                "Shot on iPhone 3G.",
                "I didn't know Gameboy Camera was making a comeback.",
                "Are you made of pixels?",
                "Is this a smudge or a person?",
                "Did you take this during an earthquake?",
                "Wipe your lens, greasy.",
                "This resolution is disrespectful.",
                "I can count the pixels on one hand.",
                "Lighting budget: $0.",
                "Are you in a cave?",
                "This photo needs subtitles.",
                "I feel like I need 3D glasses for this.",
                "Are you hiding from the light?",
                "Blurrier than my vision without glasses.",
                "This looks like a leaked cursed image.",
                "Did you screen record a potato?",
                "Vintage aesthetic or just bad tech?",
                "I've seen better quality on a bank security camera.",
                "Are you a Bigfoot sighting?",
                "Rendering... 10% complete.",
                "Try turning on the lights next time."
            ],
            'no-mercy': [
                "This photo has less clarity than your life choices.",
                "I can't tell if this is a selfie or a screenshot from a cursed VHS tape.",
                "Batman called, he wants his brooding darkness back.",
                "Did you take this with a toaster?",
                "Your camera quality matches your personality: dull.",
                "You look like a deep-fried meme.",
                "I've seen better resolution on a pregnancy test.",
                "This photo makes my GPU hurt.",
                "If I wanted to see a blur, I'd take off my glasses.",
                "You look like a blocked character in a video game.",
                "The darkness isn't hiding your ugliness, nice try.",
                "This looks like it was taken in the Upside Down.",
                "Are you allergic to HD?",
                "You look like a buffering video meant to be skipped.",
                "This image is a crime against photography.",
                "Even the autofocus gave up on you.",
                "You look like a glitch in the simulation.",
                "I can smell the low bitrate from here.",
                "Your phone camera is crying for help.",
                "This looks like a screenshot of a screenshot of a thumb.",
                "You put the 'low' in low definition.",
                "Is this a Rorschach test?",
                "I can't roast what I can't see, but I assume it's bad.",
                "You look like visual static.",
                "Try cleaning your lens, or your face."
            ],
            'career-ending': [
                "You look like an unlockable character that nobody wants to unlock.",
                "If depression was a camera setting, it would be this.",
                "Your face is buffering.",
                "I've seen UFO footage with better resolution.",
                "You look like the embodiment of dial-up internet.",
                "This quality is offensive to my sensors.",
                "You look like a faded memory nobody wants to keep.",
                "This photo has the same clarity as your future.",
                "You're fading away like your relevance.",
                "I assume you made this blurry on purpose to hide the truth.",
                "This is the visual equivalent of mumble rap.",
                "You look like a mistake that's being erased.",
                "Low quality image for a low quality person.",
                "You look like a corrupted file.",
                "I'd ask for a re-upload, but I don't want to see you in HD.",
                "Your vibe is 'found footage horror movie victim'.",
                "You look like pending doom.",
                "Nothing says 'I gave up' like this lighting.",
                "You are the definition of obscure.",
                "This photo has negative aura.",
                "You look like a bad dream recorded on VHS.",
                "I've seen better lighting in a coffin.",
                "You look like a smudged fingerprint.",
                "This is pathetic in 144p.",
                "Delete this before the internet sees it."
            ]
        }
    },
    {
        category: "fake_smile",
        weight: 1.5,
        condition: (s) => s.faceDetected && s.smileScore > 0.4 && s.smileScore < 0.7 && s.eyeOpenness > 0.4,
        templates: {
            'playful': [
                "That smile says 'I'm fine' but the eyes scream 'help me'.",
                "Practicing for school picture day?",
                "Show us your real teeth, coward.",
                "Blink twice if you're in danger.",
                "You smile like a Sims character.",
                "Aw, look at you trying to be human.",
                "That smile is holding on by a thread.",
                "You look like you just ate a lemon.",
                "Who forced you to take this?",
                "That's a 'I just farted' smile.",
                "You look like you're hiding a secret.",
                "Trying too hard, bestie.",
                "You smile like a politician.",
                "Is that tape holding your cheeks up?",
                "You look like a nervous chihuahua.",
                "Smile rating: 3/10. try again.",
                "You look like you're in physical pain.",
                "That's the face of 'I forgot my wallet'.",
                "You smile like you're at the dentist.",
                "Cringe check passed.",
                "You look like a stock photo for 'mild discomfort'.",
                "That smile is loading...",
                "You look suspicious.",
                "Fake it til you make it, I guess?",
                "You look like you're holding your breath."
            ],
            'no-mercy': [
                "You smile like you're being held hostage at gunpoint.",
                "This is the face of someone who just remembered a cringe memory from 2012.",
                "Your mouth says cheese, but your soul says existential dread.",
                "That smile is faker than your personality.",
                "You look like a malfunctioning robot trying to blend in.",
                "I can see the pain behind those eyes.",
                "You smile like you owe money.",
                "Keep smiling, maybe the sadness will go away.",
                "You look like you just got roasted by a 12-year-old.",
                "That smile is a cry for help.",
                "You look like you're suppressing a scream.",
                "Your face says 'happy', your vibe says 'therapy'.",
                "This is the smile of someone who peaked in high school.",
                "You look like you're rebooting.",
                "That smile is about as genuine as a gas station sushi roll.",
                "You look like you're watching your house burn down.",
                "Dead inside, but make it fashion.",
                "You smile like you're apologizing for existing.",
                "This is the most uncomfortable image on the internet.",
                "You look like you just read your own search history.",
                "That's a panic smile if I ever saw one.",
                "You look like you're trying to sell me a pyramid scheme.",
                "Your smile is a lie.",
                "You look like you're about to crack.",
                "The uncanny valley called, they want you back."
            ],
            'career-ending': [
                "That is the most customer-service-rep smile I have ever seen.",
                "You look like a skinwalker trying to mimic human joy and failing.",
                "There is absolutely zero light behind those eyes.",
                "You smile like a sociopath practicing in the mirror.",
                "I've never seen a smile essentially divide by zero before.",
                "Your happiness looks like a glitch.",
                "You look like a doll that comes alive at night to steal souls.",
                "This smile triggers my fight or flight response.",
                "You look like you're wearing someone else's face.",
                "That smile is the visual definition of despair.",
                "You look like the villain before the reveal.",
                "Your face is frozen in a silent scream.",
                "I don't trust you.",
                "You look like you enjoy listening to static.",
                "That smile has negative warmth.",
                "You look like an AI generation that went wrong.",
                "This is pure nightmare fuel.",
                "You smile like you just buried a body.",
                "Your expression is a void.",
                "I feel cold looking at this.",
                "You look like a wax figure melting.",
                "That's the smile of a broken spirit.",
                "You look like you're dissociating hard.",
                "This is what 'dead inside' looks like in HD.",
                "Stop smiling, you're scaring the children."
            ]
        }
    },
    {
        category: "dead_eyes",
        weight: 1.8,
        condition: (s) => s.faceDetected && s.eyeOpenness < 0.35,
        templates: {
            'playful': [
                "Wake up bestie, the roast is starting.",
                "You look like you've been awake for 72 hours straight.",
                "Sleep is important. Try it sometime.",
                "Are your eyes on low power mode?",
                "You look like a sleepy sloth.",
                "Did you blink? Or is this just your face?",
                "Nap time was an hour ago.",
                "Open your eyes, the world isn't that bright.",
                "You look like you just woke up from a 10-year coma.",
                "Too tired to function?",
                "You look like a vampire on a day shift.",
                "Are you meditating or just bored?",
                "Your eyes are buffering.",
                "You look high on life... or Benadryl.",
                "Squinting won't make you look cooler.",
                "You look like you're allergic to sunlight.",
                "Rise and shine, zombie.",
                "You look cozy but also confused.",
                "Eye.exe has stopped working.",
                "You look like a tired pug.",
                "Dreaming of a better roast?",
                "You look like you need a Red Bull IV drip.",
                "Lights are on, nobody's home.",
                "You look soft, like a pillow.",
                "Are you reading the fine print on my soul?"
            ],
            'no-mercy': [
                "You look like a zombie that gave up on eating brains because it's too much effort.",
                "I've seen more life in a tax return.",
                "Are you squinting or do you just hate everything you see?",
                "You look like you just attended a 4-hour Zoom meeting.",
                "The lights are off and nobody is home.",
                "You look like a recovering raccoon.",
                "Your eyes are giving 'battery low'.",
                "You look permanently exhausted by existence.",
                "I'd offer you coffee but I think you need an ambulance.",
                "You look like the 'before' photo of a sleep apnea commercial.",
                "Your energy is nonexistent.",
                "You look depleted.",
                "Did you sell your soul for a nap?",
                "You look like you're haunting your own body.",
                "I can see your dreams dying in real time.",
                "You look like you're powered by dial-up.",
                "Your eyes are social distancing from your eyelids.",
                "You look like a melted candle.",
                "You look like you're buffering in real life.",
                "Even your eyes are lazy.",
                "You look like you're watching paint dry.",
                "You look like a deflated balloon.",
                "Wake up, you're ruining the vibe.",
                "You look like you're fading from existence.",
                "Your face says 'loading', your eyes say 'error'."
            ],
            'career-ending': [
                "You look like the 'after' photo of a failed crypto investor.",
                "I didn't know it was possible to look bored and panicked at the same time.",
                "Your eyes are closed because you can't bear to look at your own reflection.",
                "You look like a corpse that forgot to fall down.",
                "Your eyes have the same liveliness as a dead fish.",
                "You look like you've seen things... terrible, boring things.",
                "This is the face of unconditional surrender.",
                "You look like you've been hollowed out.",
                "There is nothing behind those eyes. Absolutely nothing.",
                "You look like a failed experiment.",
                "Your soul left the chat ages ago.",
                "You look like you're decaying.",
                "I've never seen such high-definition apathy.",
                "You look like you're expiring.",
                "Your gaze is a black hole of charisma.",
                "You look like a walking burnout.",
                "This is what giving up looks like.",
                "You look like a ghost haunting a DMV.",
                "Your eyes are voids of despair.",
                "You look like you've been drained of all joy.",
                "I'd check your pulse but I don't think you have one.",
                "You look like you're waiting for the sweet release of death.",
                "Your stare makes me depressed.",
                "You look like an unplugged appliance.",
                "Total system failure in the eyes."
            ]
        }
    },
    {
        category: "too_happy",
        weight: 1.6,
        condition: (s) => s.faceDetected && s.smileScore > 0.7,
        templates: {
            'playful': [
                "What are you smiling about? Do you know something we don't?",
                "You look like you just won a participation trophy.",
                "Easy there, sunshine. Save some joy for the rest of us.",
                "You're glowing! Like a radioactive waste site.",
                "Did you just eat a cookie?",
                "Too much glitter, tone it down.",
                "You look like a happy clam.",
                "Someone's had their coffee today.",
                "You look like a Disney adult.",
                "Are you auditioning for a toothpaste commercial?",
                "You look like a kid in a candy store.",
                "Who's a good boy? You are!",
                "You look like you just found $5.",
                "That smile is wider than my future.",
                "You look like a happy emoji IRL.",
                "Did you win the lottery or are you just like this?",
                "You smile like a golden retriever.",
                "Sparkles are flying off you.",
                "You look suspiciously happy.",
                "Did you break something?",
                "You look like a morning person (derogatory).",
                "Chill with the serotonin.",
                "You look like you love Mondays.",
                "Are you high on life?",
                "You look like a cupcake."
            ],
            'no-mercy': [
                "You smile like a golden retriever that just ate a bee.",
                "Ignorance is bliss, and you look absolutely euphoric.",
                "Stop smiling. It's unsettling.",
                "You look like a cult leader recruiting for a pyramid scheme.",
                "You look like you capture live laugh love signs.",
                "That smile is manic.",
                "You look like you're about to snap.",
                "Nobody is this happy, seek help.",
                "You smile like a gameshow host who hates their life.",
                "You look like you're overcompensating.",
                "Your joy is annoying.",
                "You look like a frantic cheerleader.",
                "That smile is unhinged.",
                "You look like a overly attached girlfriend meme.",
                "Calm down, Joker.",
                "You look like you just hid a body and are proud.",
                "That happiness feels illegal.",
                "You look like a mascot without the suit.",
                "Your face hurts to look at.",
                "You smile like a car salesman.",
                "You look like you're mocking me.",
                "That's a 'bless your heart' smile.",
                "You look like a youth pastor.",
                "You look like you believe in crystals.",
                "Your energy is exhausting."
            ],
            'career-ending': [
                "That smile is the visual equivalent of comic sans.",
                "You look like the 'before' picture in a medication commercial.",
                "I haven't seen toxic positivity captured so perfectly in one image.",
                "You look like a sleep paralysis demon pretending to be nice.",
                "That smile is the last thing people see before they go missing.",
                "You look like the Joker's understudy.",
                "Your face is a warning label.",
                "I'd rather stare at the sun than your smile.",
                "You look like a doll possessed by a demon.",
                "Your happiness is terrifying.",
                "You look like a pure psychopath.",
                "That smile is a threat.",
                "You look like you'd kill for a discount.",
                "Your face screams 'I need supervision'.",
                "You look like a horror movie jumpscare.",
                "That smile creates a void in my soul.",
                "You look like you eat glue.",
                "Your expression is a crime.",
                "I feel unsafe looking at this.",
                "You look like a clown in a sewer.",
                "That smile is a glitch in the matrix.",
                "You look like you're screaming inside.",
                "Your joy is my nightmare.",
                "You look like a forgotten puppet.",
                "Delete this face."
            ]
        }
    },
    {
        category: "too_serious",
        weight: 1.6,
        condition: (s) => s.faceDetected && s.smileScore < 0.2,
        templates: {
            'playful': [
                "Why the long face?",
                "You look like you just read the Terms and Conditions.",
                "Cheer up, it's just a roast. Or is it?",
                "Did someone steal your lunch?",
                "You look like a grumpy cat.",
                "Smile! It confuses people.",
                "You look like you need a hug.",
                "Are you doing a staring contest?",
                "You look like a stern librarian.",
                "Thinking about taxes?",
                "You look like a bouncer at a club nobody goes to.",
                "Serious mode: ON.",
                "You look like you're judging my soul.",
                "Did you forget how to smile?",
                "You look like a disappointed parent.",
                "Are you solving a math problem?",
                "You look like you smelled something bad.",
                "Hard day at the office?",
                "You look like a bond villain's henchman.",
                "Try not to look so excited.",
                "You look like you're on hold with customer service.",
                "Are you buffering?",
                "You look like a statue.",
                "Poker face champion.",
                "You look like you hate fun."
            ],
            'no-mercy': [
                "You have the resting face of a DMV employee.",
                "You look like you're waiting for a bus that's never coming.",
                "If 'Monday morning' was a person, it would be you.",
                "You look like a wet blanket.",
                "Your vibe is 'fun vampire'.",
                "You look like you ruin parties.",
                "Smile, it won't crack your face.",
                "You look like a joy vacuum.",
                "Your aura is grey.",
                "You look like you complain to the manager.",
                "You look like you audit taxes for fun.",
                "Your face is a mood killer.",
                "You look like a disappointed dad.",
                "You look like you hate puppies.",
                "I bet you're fun at parties (lie).",
                "You look like you judge people for breathing.",
                "Your expression is a buzzkill.",
                "You look like a karen in training.",
                "You look like you eat plain toast.",
                "Your personality is cardboard.",
                "You look like you're allergic to joy.",
                "You look like a rainy day.",
                "You look like a walking sigh.",
                "Your face says 'get off my lawn'.",
                "You look like you enjoy waiting in line."
            ],
            'career-ending': [
                "Your expression has single-handedly lowered the mood of the entire internet.",
                "You look like you just watched your investment portfolio hit zero.",
                "I promise you, being this edgy is not a personality.",
                "You look like a funeral director having a bad day.",
                "Your face is the definition of mediocrity.",
                "You look like you've never felt joy in your life.",
                "You look like a soulless bureaucrat.",
                "Your stare is void of all humanity.",
                "You look like a gargoyle.",
                "Your expression creates a vacuum of happiness.",
                "You look like you embody the concept of rejection.",
                "I've seen happier crash test dummies.",
                "You look like you're made of stone.",
                "Your face is a tragedy.",
                "You look like you're dead inside and out.",
                "You look like a prison warden.",
                "Your vibe is 'clinical depression'.",
                "You look like a rejected passport photo.",
                "You look like you're judging god.",
                "Your face is a brick wall.",
                "You look like you've given up.",
                "You look like a math textbook cover.",
                "Your existence feels heavy.",
                "You look like a cancelled TV show.",
                "Your face is a literal stop sign."
            ]
        }
    },
    {
        category: "basic_vibe",
        weight: 1.0, // Fallback
        condition: () => true,
        templates: {
            'playful': [
                "You look like you remind the teacher to collect homework.",
                "Your vibe is very 'background character in a low-budget sitcom'.",
                "I didn't know beige was a personality trait until I saw this picture.",
                "You look like you enjoy oatmeal.",
                "You're the human equivalent of tap water.",
                "You look like a default skin.",
                "You look like you follow all the rules.",
                "Your favorite spice is flour.",
                "You look like you buy generic brands.",
                "You look like you drive the speed limit.",
                "You look like a stock photo for 'person'.",
                "You look like you say 'okie dokie'.",
                "You look like you iron your socks.",
                "You look like you use a flip phone.",
                "You look like you enjoy waiting rooms.",
                "You look like you own a label maker.",
                "You look like you're 'just happy to be here'.",
                "You look like you clap when the plane lands.",
                "You look like you drink milk with dinner.",
                "You look like a nice person (boring).",
                "You look like you have a Live Laugh Love sign.",
                "You look like you fold your pizza.",
                "You look like you wear socks with sandals.",
                "You look like you remind people to hydrate.",
                "You look like a tutorial level."
            ],
            'no-mercy': [
                "I've seen better style on a randomized Sim.",
                "If 'unseasoned chicken' was a person, it would be you.",
                "You look like you peaked in middle school.",
                "This outfit screams 'my mom bought this for me'.",
                "You have the personality of a wet napkin.",
                "You look like a placeholder.",
                "You look like an NPC that got stuck.",
                "You look like you're buffering.",
                "Your vibe is 'waiting room magazine'.",
                "You look like you get lost in grocery stores.",
                "You look like you ask for the manager nicely.",
                "You look like you apologize to furniture.",
                "You look like you have zero rizz.",
                "You look like the 'after' in a weight watchers ad.",
                "You look like you enjoy filing taxes.",
                "You look like you're afraid of spicy food.",
                "You look like you button the top button.",
                "You look like you wear cargo shorts.",
                "You look like you check the weather app hourly.",
                "You look like you're basic and proud.",
                "You look like a targeted ad for boring people.",
                "You look like you collect dust.",
                "You look like you're about to sneeze.",
                "You look like a background extra.",
                "You look like you're easily confused."
            ],
            'career-ending': [
                "Your face is the reason incognito mode was invented.",
                "Proof that evolution sometimes takes a step back.",
                "You look like a glitched NPC that the developers forgot to delete.",
                "I'd roast you but life clearly already did.",
                "You look like human tofu.",
                "You are the definition of forgettable.",
                "You look like an abandoned project.",
                "Your existence is mild.",
                "You look like a participation trophy come to life.",
                "You look like a typo in the genetic code.",
                "You look like a rejected concept art.",
                "You look like you have negative charisma.",
                "You look like a walking dial tone.",
                "You look like a loading screen that never loads.",
                "You look like empty space.",
                "You look like a filler episode.",
                "You look like a budget cut.",
                "You look like a generic brand human.",
                "You look like you were designed by committee.",
                "You look like a cancelled subscription.",
                "You look like a corrupted save file.",
                "You look like a 404 page.",
                "You look like pure mediocrity.",
                "You look like a blank sheet of paper.",
                "You look like a wasted opportunity."
            ]
        }
    }
];

export function generateSavageRoast(signals: ImageSignals, intensity: string): string {
    // 1. Filter applicable categories
    const validCategories = ROAST_TEMPLATES.filter(t => t.condition(signals));

    // 2. Sort by weight + randomness
    // We want high weight items to appear more often, but still be random.
    // Let's create a weighted pool.
    const pool: string[] = [];

    validCategories.forEach(cat => {
        // Add templates multiple times based on weight
        const templates = cat.templates[intensity as keyof typeof cat.templates] || cat.templates['no-mercy'];
        const count = Math.ceil(cat.weight * 3);
        for (let i = 0; i < count; i++) {
            pool.push(...templates);
        }
    });

    // 3. Pick random
    if (pool.length === 0) return "You look so boring I can't even roast you.";

    return pool[Math.floor(Math.random() * pool.length)];
}
