import type { ImageSignals } from './imageAnalysis';

interface RoastTemplate {
    category: string;
    weight: number;
    condition: (s: ImageSignals) => boolean;
    templates: { [key: string]: string[] }; // keyed by intensity
}

const ROAST_TEMPLATES: RoastTemplate[] = [
    {
        category: "no_face",
        weight: 10.0,
        condition: (s) => !s.faceDetected,
        templates: {
            'playful': [
                "I'd hide my face too if I were you.",
                "You're playing hide and seek, but nobody is seeking.",
                "Did you forget to show up to your own life?",
                "This photo has as much personality as a wet napkin.",
                "I see a wall, a floor, and a lot of regret.",
                "Are you a vampire? Or just allergic to mirrors?",
                "You're elusive, like a good credit score.",
                "This picture is almost as empty as your weekend plans.",
                "I'm roasting the air, and even it has more substance than you.",
                "You're gone, just like your potential.",
                "Did you take this while running away from your problems?",
                "I can't see you, but I can feel the disappointment.",
                "Is this a photo of your friends? Oh wait, it's empty.",
                "You're not camera shy, the camera is just you-shy.",
                "I assume you're the furniture, because you have the same charisma.",
                "Nice background, shame about the missing person.",
                "You're like a magician, making yourself disappear from relevance.",
                "This is a masterpiece of nothingness.",
                "You clearly didn't want to be seen, and I thank you for that.",
                "I'd ask where you are, but I don't really care.",
                "You're hiding like you owe the cameraman money.",
                "This photo is as vacant as your stare.",
                "Did you accidentally take this with your elbow?",
                "You're doing the world a favor by staying out of frame."
            ],
            'no-mercy': [
                "Your dad left because he didn't want to look at you either.",
                "You're not important enough to be seen.",
                "This photo is a waste of storage space, just like you're a waste of oxygen.",
                "I'm glad you're not in this, it would have ruined my appetite.",
                "You have the presence of a silent fart.",
                "Nobody notices when you leave the room, just like this photo.",
                "You're as memorable as a tuesday afternoon.",
                "The camera lens refused to open for you.",
                "You're avoiding the camera like you avoid your responsibilities.",
                "This is the most interesting you've ever looked: invisible.",
                "I'd roast you, but you're not even worth the effort of locating.",
                "You're so insignificant, even the auto-focus ignored you.",
                "It's better this way. Nobody needs to see that mug.",
                "You're hiding your face because deep down, you know.",
                "An empty room has more value than your company.",
                "You're like a ghost, but without the interesting backstory.",
                "This void is still better looking than you.",
                "You've successfully erased yourself, congratulations.",
                "I bet your parents wish you were this invisible all the time.",
                "You're doing a great job of not existing.",
                "This is exactly how much impact you have on the world.",
                "A blank screen is an upgrade compared to your face.",
                "You're the human equivalent of a skipped track."
            ],
            'career-ending': [
                "Your absence in this photo is the best contribution you've ever made.",
                "The world is a slightly better place when you're not visible.",
                "You're not even a main character in your own selfie.",
                "This is what your friends see when they close their eyes: relief.",
                "You effectively don't exist. And we prefer it that way.",
                "If you were missing, nobody would put your face on a milk carton.",
                "You've achieved the perfect look: absent.",
                "I tried to find you, but I found my self-respect instead.",
                "You are the definition of negligible.",
                "Even your reflection quit out of sheer boredom.",
                "You're the side character that gets cut from the final edit.",
                "This photo captures your essence perfectly: nothing.",
                "You're so irrelevant it actually hurts.",
                "A black hole has more radiance than you.",
                "You're not missing, you're just not wanted.",
                "This is the visual representation of your achievements.",
                "You're a void where a person should be.",
                "You're the human equivalent of an empty inbox.",
                "I've seen more life in a cemetery.",
                "You're not hiding, you're just being erased.",
                "This is a preview of your funeral: nobody showing up.",
                "You're as essential as a screen door on a submarine.",
                "Go ahead, stay hidden. It's better for everyone."
            ]
        }
    },
    {
        category: "bad_quality",
        weight: 2.0,
        condition: (s) => s.isDark || s.blurScore < 0.2,
        templates: {
            'playful': [
                "Did you take this with a potato?",
                "Clean your room before you take photos.",
                "My grandma takes better photos than this, and she's blind.",
                "Is this a photo or a smudge on my screen?",
                "You look like a blurry cryptid sighting.",
                "Did you take this during an earthquake?",
                "Wipe your lens, you greasy mess.",
                "I can't tell if that's your face or a dirty thumbprint.",
                "Did you pay for this camera? You got ripped off.",
                "This looks like it was taken inside a toaster.",
                "Are you allergic to good lighting?",
                "This resolution is lower than your grades.",
                "I didn't know they made cameras this bad anymore.",
                "You look like you're being censored.",
                "Is this an abstract painting of 'failure'?",
                "Focus is a feature, you should try it.",
                "You look like a foggy bathroom mirror.",
                "Did you take this underwater?",
                "This photo is as clear as mud.",
                "You look like a stain.",
                "Are you trying to hide your ugly?",
                "This looks like a screenshot of a screenshot.",
                "Turn on a light, you cave goblin.",
                "You look like a fuzzy memory."
            ],
            'no-mercy': [
                "Your future is as dim as this lighting.",
                "This quality is almost as bad as your life choices.",
                "You look like a mistake that's being erased.",
                "Did you take this with a security camera from 1990?",
                "Accept it, no amount of blur will hide your ugliness.",
                "You look like a deep-fried failure.",
                "I've seen better resolution on a pregnancy test.",
                "This photo is a crime against eyes.",
                "You look like a glitch in the simulation, a bad one.",
                "Even the camera gave up on focusing on you.",
                "You look like a majestic blob of nothing.",
                "This is the visual equivalent of mumble rap.",
                "You look like you're fading away, thankfully.",
                "This photo smells like poverty.",
                "You look like a dusty old relic.",
                "I can't even roast you properly, you're just a blur.",
                "You look like a blocked contact.",
                "This is pathetic. Try harder.",
                "You look like a smudge on society.",
                "I assume you made this blurry to protect us.",
                "You're not mysterious, you're just bad at photography.",
                "This looks like evidence from a crime scene.",
                "You look like a bad dream."
            ],
            'career-ending': [
                "You look like a faded memory nobody wants to keep.",
                "This photo has the same clarity as your non-existent love life.",
                "You look like a corrupted file that ruined the whole drive.",
                "I'd ask for a re-upload, but I really don't want to see you in HD.",
                "You look like the 'before' picture of a tragedy.",
                "This is offensive to my sensors and my taste.",
                "You look like something I'd scrape off my shoe.",
                "You're fading into obscurity right before our eyes.",
                "This is the highest quality you'll ever achieve.",
                "You look like an accident waiting to happen.",
                "This blurry mess is the highlight of your year.",
                "You look like a discarded wrapper.",
                "Nobody wants to see this clearly. Trust me.",
                "You look like a mistake.",
                "This is what failure looks like in low resolution.",
                "You're not even worth the pixels.",
                "You look like a bad omen.",
                "You're a smudge on the lens of life.",
                "This is visual garbage.",
                "You look like a forgotten thought.",
                "Just delete this. And yourself.",
                "You look like a regret.",
                "The darkness suits you. Stay there."
            ]
        }
    },
    {
        category: "fake_smile",
        weight: 1.5,
        condition: (s) => s.faceDetected && s.smileScore > 0.4 && s.smileScore < 0.7 && s.eyeOpenness > 0.4,
        templates: {
            'playful': [
                "You smile like you're about to ask me for money.",
                "That smile is as fake as your designer bag.",
                "You look like you're holding in a sermon.",
                "Stop forcing it, nobody believes you.",
                "You smile like a toddler who just pooped their pants.",
                "Blink twice if you're being held hostage.",
                "You look like you're in physical pain.",
                "That's the face of 'I forgot my wallet'.",
                "You smile like a politician on a scandal tour.",
                "Is that a smile or a grimace?",
                "You look like you just ate a lemon.",
                "Trying too hard, sweaty.",
                "You smile like a nervous chihuahua.",
                "You look like you're hiding a secret: you're boring.",
                "That smile is holding on by a thread.",
                "You look like a stock photo for 'uncomfortable'.",
                "Who has a gun to your head?",
                "You look suspicious.",
                "Fake it til you make it, I guess?",
                "You look like you're holding your breath.",
                "That's a 'I just farted' smile.",
                "You smile like you're at the dentist.",
                "You look like you're trying to sell me essential oils.",
                "Your face says cheese, your eyes say help."
            ],
            'no-mercy': [
                "That smile is faker than your parents' love for you.",
                "You look like you're being held hostage by your own mediocrity.",
                "Your mouth says happy, but your eyes say dead inside.",
                "You look like a malfunctioning robot.",
                "I can see the desperation in your teeth.",
                "You smile like you owe money to bad people.",
                "Keep smiling, maybe the sadness will go away.",
                "You look like you just remembered a cringe memory.",
                "That smile is a cry for help.",
                "You look like you're suppressing a scream.",
                "Your face is a lie.",
                "You look like you're watching your house burn down.",
                "This is the most uncomfortable thing I've seen all day.",
                "You smile like you're apologizing for existing.",
                "You look like a psychopath practicing emotions.",
                "That smile is about as genuine as a spam email.",
                "You look like you're about to crack.",
                "You smile like a Stepford wife.",
                "You look like you're dead inside.",
                "Your happiness looks painful.",
                "You look like a clown without makeup.",
                "Stop smiling, it's creepy.",
                "You look like a fraud.",
                "Your face hurts to look at."
            ],
            'career-ending': [
                "You smile like a sociopath shortly after the crime.",
                "There is absolutely zero light behind those eyes.",
                "You look like a doll that comes alive to steal souls.",
                "This smile triggers my fight or flight response.",
                "You look like you're wearing someone else's face.",
                "That smile is the visual definition of despair.",
                "You look like the villain before the reveal.",
                "Your face is frozen in a silent scream.",
                "I don't trust you, and neither does your dog.",
                "You look like you enjoy listening to static.",
                "That smile has negative warmth.",
                "You look like a failed experiment.",
                "This is pure nightmare fuel.",
                "You smile like you just buried a body.",
                "Your expression is a void.",
                "I feel cold looking at this.",
                "You look like a wax figure melting.",
                "That's the smile of a broken spirit.",
                "You look like you're dissociating hard.",
                "This is what 'gave up' looks like.",
                "Stop smiling, you're scaring the children.",
                "You look like a bad actor.",
                "Your joy is a lie."
            ]
        }
    },
    {
        category: "dead_eyes",
        weight: 1.8,
        condition: (s) => s.faceDetected && s.eyeOpenness < 0.35,
        templates: {
            'playful': [
                "Wake up, your life is passing you by.",
                "You look like you just got fired.",
                "Sleep is for the weak, and you look very weak.",
                "Are your eyes on low power mode?",
                "You look like a sleepy sloth.",
                "Did you blink? Or is this just your face?",
                "Nap time was an hour ago, toddler.",
                "Open your eyes, the world isn't that bright.",
                "You look like you just woke up from a coma.",
                "Too tired to function?",
                "You look like a vampire on a day shift.",
                "Are you meditating or just slow?",
                "Your eyes are closed to hide the shame.",
                "You look high on life... or something else.",
                "Squinting won't make you look smarter.",
                "You look like you're allergic to mornings.",
                "Rise and shine, zombie.",
                "You look cozy but also useless.",
                "You look like a tired pug.",
                "Dreaming of being attractive?",
                "You look like you need a coffee IV drip.",
                "Lights are on, nobody's home.",
                "You look soft, like a pillow.",
                "Are you reading the back of your eyelids?"
            ],
            'no-mercy': [
                "You have the energy of a damp mop.",
                "You look like you've given up on everything.",
                "I've seen more life in roadkill.",
                "You look like a zombie that's too lazy to hunt.",
                "The lights are off and the house is abandoned.",
                "You look like a recovering raccoon.",
                "Your eyes are empty, just like your head.",
                "You look permanently exhausted by your own existence.",
                "I'd offer you coffee but you need a miracle.",
                "You look like the 'before' photo of a sleep clinic.",
                "Your energy is nonexistent.",
                "You look depleted of all worth.",
                "Did you sell your soul for a nap?",
                "You look like you're haunting your own body.",
                "I can see your dreams dying in real time.",
                "You look like you're powered by a potato battery.",
                "Your eyes are divorcing your face.",
                "You look like a melted candle.",
                "You look like you're buffering.",
                "Even your eyes are lazy.",
                "You look like you're watching paint dry.",
                "You look like a deflated balloon.",
                "Wake up, you're ruining the vibe.",
                "You look like you're fading away."
            ],
            'career-ending': [
                "You look like the 'after' photo of a failed life.",
                "Your eyes are closed because you can't bear to look at yourself.",
                "You look like a corpse that forgot to fall down.",
                "Your eyes have the same liveliness as a dead fish.",
                "You look like you've seen things... mostly your own failures.",
                "This is the face of unconditional surrender.",
                "There is nothing behind those eyes. Absolutely nothing.",
                "You look like a failed experiment.",
                "Your soul left the chat years ago.",
                "You look like you're decaying.",
                "I've never seen such high-definition apathy.",
                "You look like you're expiring.",
                "Your gaze is a black hole.",
                "You look like a walking burnout.",
                "This is what giving up looks like.",
                "You look like a ghost haunting a DMV.",
                "Your eyes are voids of despair.",
                "You look like you've been drained of all joy.",
                "I'd check your pulse but I don't think you have one.",
                "You look like you're waiting for the end.",
                "Your stare makes me depressed.",
                "You look like an unplugged appliance.",
                "Total system failure."
            ]
        }
    },
    {
        category: "too_happy",
        weight: 1.6,
        condition: (s) => s.faceDetected && s.smileScore > 0.7,
        templates: {
            'playful': [
                "You look like the neighbor everyone avoids.",
                "Nobody likes people this happy.",
                "You look like you just keyed someone's car.",
                "Wipe that smirk off your face.",
                "You look like a game show host on crack.",
                "What are you smiling about? You're broke.",
                "Easy there, sunshine. You're blinding me.",
                "You're glowing! Like radioactive sludge.",
                "Did you just eat a bird?",
                "Too much energy, take a nap.",
                "You look like a Disney adult.",
                "Are you auditioning for a cult?",
                "You look like a kid in a candy store.",
                "Who's a good boy? You are!",
                "You look like you found a dollar.",
                "That smile is bigger than your brain.",
                "You look like an emoji.",
                "Did you win the lottery? Can I have some?",
                "You smile like a golden retriever.",
                "You look suspiciously happy.",
                "Did you break something?",
                "You look like a morning person (gross).",
                "Chill with the happiness.",
                "You look like you love Mondays."
            ],
            'no-mercy': [
                "You look like a psychopath who just got away with it.",
                "Your happiness is offensive to everyone.",
                "Ignorance is bliss, and you look ecstatic.",
                "Stop smiling. It's unsettling.",
                "You look like a cult leader.",
                "You look like you buy 'live laugh love' signs.",
                "That smile is manic. Seek help.",
                "You look like you're about to snap.",
                "Nobody is this happy, you liar.",
                "You smile like a car salesman.",
                "You look like you're overcompensating.",
                "Your joy is annoying.",
                "You look like a frantic cheerleader.",
                "That smile is unhinged.",
                "You look like an overly attached girlfriend.",
                "Calm down, Joker.",
                "You look like a mascot.",
                "Your face hurts to look at.",
                "You look like you're mocking me.",
                "That's a 'bless your heart' smile.",
                "You look like a youth pastor.",
                "You look like you believe in crystals.",
                "Your energy is exhausting.",
                "You look like you eat glue."
            ],
            'career-ending': [
                "You look like a sleep paralysis demon pretending to be nice.",
                "That smile is the last thing people see before they go missing.",
                "You look like the Joker's understudy.",
                "Your face is a warning label.",
                "I'd rather stare at the sun than your smile.",
                "You look like a doll possessed by a demon.",
                "Your happiness is terrifying.",
                "You look like a pure psychopath.",
                "That smile is a threat.",
                "You look like you'd kill for a coupon.",
                "Your face screams 'I need supervision'.",
                "You look like a horror movie jumpscare.",
                "That smile creates a void in mine.",
                "Your expression is a crime.",
                "I feel unsafe looking at this.",
                "You look like a clown in a sewer.",
                "That smile is a mistake.",
                "You look like you're screaming inside.",
                "Your joy is my nightmare.",
                "You look like a forgotten puppet.",
                "Delete this face.",
                "You look like a nightmare.",
                "You're scary."
            ]
        }
    },
    {
        category: "too_serious",
        weight: 1.6,
        condition: (s) => s.faceDetected && s.smileScore < 0.2,
        templates: {
            'playful': [
                "You look like you yell at cashiers.",
                "You're the reason people leave the party early.",
                "You look like a disappointed parent.",
                "Why the long face? Evolution?",
                "You look like you just read a parking ticket.",
                "Cheer up, it could be worse. You could be you.",
                "Did someone steal your lunch?",
                "You look like a grumpy cat.",
                "Smile! It confuses people.",
                "You look like you need a hug.",
                "Are you staring into the abyss?",
                "You look like a strict librarian.",
                "Thinking about taxes?",
                "You look like a bouncer at a bingo hall.",
                "Serious mode: ON.",
                "You look like you're judging me.",
                "Did you forget how to smile?",
                "Are you solving a math problem?",
                "You look like you smelled a fart.",
                "Hard day at the doing nothing factory?",
                "You look like a villain's henchman.",
                "Try not to look so excited.",
                "You look like you're on hold.",
                "Are you buffering?"
            ],
            'no-mercy': [
                "You have the personality of a wet cardboard box.",
                "You look like you somehow ruin fun just by existing.",
                "Your resting face is a tragedy.",
                "You have the resting face of a DMV employee.",
                "You look like you're waiting for a bus that's never coming.",
                "If 'Monday morning' was a person, it would be you.",
                "You look like a wet blanket.",
                "Your vibe is 'fun vampire'.",
                "You look like you ruin parties.",
                "Smile, it won't crack your face.",
                "You look like a joy vacuum.",
                "Your aura is grey.",
                "You look like you complain to the manager.",
                "You look like you audit taxes for fun.",
                "Your face is a mood killer.",
                "You look like you hate puppies.",
                "I bet you're fun at parties (lie).",
                "You look like you judge people for breathing.",
                "Your expression is a buzzkill.",
                "You look like a karen in training.",
                "You look like you eat plain toast.",
                "Your personality is cardboard.",
                "You look like you're allergic to joy.",
                "You look like a rainy day."
            ],
            'career-ending': [
                "Your expression has single-handedly lowered the mood of the world.",
                "You look like you just watched your dreams die.",
                "I promise you, being this edgy is not a personality.",
                "You look like a funeral director.",
                "Your face is the definition of mediocrity.",
                "You look like you've never felt joy.",
                "You look like a soulless bureaucrat.",
                "Your stare is void of humanity.",
                "You look like a gargoyle.",
                "Your expression creates a vacuum of happiness.",
                "You look like you embody rejection.",
                "I've seen happier crash test dummies.",
                "You look like you're made of stone.",
                "Your face is a tragedy.",
                "You look like you're dead inside.",
                "You look like a prison warden.",
                "Your vibe is 'clinical depression'.",
                "You look like a rejected passport photo.",
                "You look like you're judging god.",
                "Your face is a brick wall.",
                "You look like you've given up.",
                "You look like a math textbook.",
                "Your existence feels heavy.",
                "You look like a cancelled show.",
                "Your face is a stop sign."
            ]
        }
    },
    {
        category: "basic_vibe",
        weight: 1.0, // Fallback
        condition: () => true,
        templates: {
            'playful': [
                "You look like every other person I've ever ignored.",
                "You have the personality of dry toast.",
                "You dress like you gave up before you started.",
                "You're about as interesting as watching grass grow.",
                "You look like you remind the teacher to collect homework.",
                "Your vibe is very 'background character'.",
                "I didn't know beige was a personality trait.",
                "You look like you enjoy oatmeal.",
                "You're the human equivalent of tap water.",
                "You look like a default skin.",
                "You look like you follow all the rules.",
                "Your favorite spice is flour.",
                "You look like you buy generic brands.",
                "You look like you drive the speed limit.",
                "You look like a stock photo.",
                "You look like you say 'okie dokie'.",
                "You look like you iron your socks.",
                "You look like you use a flip phone.",
                "You look like you enjoy waiting rooms.",
                "You look like you own a label maker.",
                "You look like you're 'just happy to be here'.",
                "You look like you clap when the plane lands.",
                "You look like you drink milk with dinner.",
                "You look like a nice person (boring)."
            ],
            'no-mercy': [
                "You are the human equivalent of unseasoned boiled chicken.",
                "If you were a color, you'd be beige.",
                "You're so forgettable I've already deleted this image from my memory.",
                "I've seen better style on a randomized Sim.",
                "You look like you peaked in middle school.",
                "This outfit screams 'my mom bought this'.",
                "You have the personality of a wet napkin.",
                "You look like a placeholder.",
                "You look like an extra.",
                "You look like you're buffering.",
                "Your vibe is 'waiting room magazine'.",
                "You look like you get lost in stores.",
                "You look like you ask for the manager.",
                "You look like you apologize to furniture.",
                "You look like you have zero game.",
                "You look like the 'after' in a weight watchers ad.",
                "You look like you enjoy filing taxes.",
                "You look like you're afraid of spicy food.",
                "You look like you button the top button.",
                "You look like you wear cargo shorts.",
                "You look like you check the weather app.",
                "You look like you're basic and proud.",
                "You look like a targeted ad.",
                "You look like you collect dust."
            ],
            'career-ending': [
                "Your face is the reason incognito mode was invented.",
                "Proof that evolution sometimes takes a step back.",
                "You look like a mistake.",
                "I'd roast you but life clearly already did.",
                "You look like human tofu.",
                "You are the definition of forgettable.",
                "You look like an abandoned project.",
                "Your existence is mild.",
                "You look like a participation trophy.",
                "You look like a typo.",
                "You look like a rejected concept.",
                "You look like you have negative charisma.",
                "You look like a dial tone.",
                "You look like a loading screen.",
                "You look like empty space.",
                "You look like a filler episode.",
                "You look like a budget cut.",
                "You look like a generic brand.",
                "You look like you were designed by committee.",
                "You look like a cancelled subscription.",
                "You look like a corrupted file.",
                "You look like a 404 page.",
                "You look like mediocrity.",
                "You look like a blank sheet.",
                "You look like a waste."
            ]
        }
    }
];

export function generateSavageRoast(signals: ImageSignals, intensity: string): string {
    // 1. Filter applicable categories
    const validCategories = ROAST_TEMPLATES.filter(t => t.condition(signals));

    // 2. Sort by weight + randomness
    // We want high weight items to appear more often, but still be random.
    // Let's create a weighted pool.
    const pool: string[] = [];

    validCategories.forEach(cat => {
        // Add templates multiple times based on weight
        const templates = cat.templates[intensity as keyof typeof cat.templates] || cat.templates['no-mercy'];
        const count = Math.ceil(cat.weight * 3);
        for (let i = 0; i < count; i++) {
            pool.push(...templates);
        }
    });

    // 3. Pick random
    if (pool.length === 0) return "You look so boring I can't even roast you.";

    return pool[Math.floor(Math.random() * pool.length)];
}
